export const discoAssets = [
  { name: "Harry", url: "harry.png" },
  { name: "Kim", url: "kim.png" },
  { name: "Yellow Plastic Bag", url: "yellowplasticbag.png" },
  { name: "Prybar", url: "prybar.png" },
  { name: "Glass Tare", url: "glasstare.png" },
  { name: "Plastic Tare", url: "plastictare.png" },

  { name: "Astra", url: "substances/astra.png" },
  { name: "Commodore Red", url: "substances/commodorered.png" },
  { name: "Goracy Brew", url: "substances/goracybrew.png" },
  { name: "Pale Aged Vodka", url: "substances/paleagedvodka.png" },
  { name: "Potent Pilsner", url: "substances/potentpilsner.png" },
  { name: "Preptide", url: "substances/preptide.png" },
  { name: "Pyrholidon", url: "substances/pyrholidon.png" },
  { name: "Speedbottle", url: "substances/speedbottle.png" },
  { name: "Tioumoutiri", url: "substances/tioumoutiri.png" },

  { name: "Disco Ball 1", url: "disco/discoball_1.png" },
  { name: "Disco Ball 2", url: "disco/discoball_2.png" },
  { name: "Disco Ball 3", url: "disco/discoball_3.png" },
  { name: "Disco Ball 4", url: "disco/discoball_4.png" },
  { name: "Disco Ball 5", url: "disco/discoball_5.png" },
  { name: "Disco Ball 6", url: "disco/discoball_6.png" },
  { name: "Disco Ball 7", url: "disco/discoball_7.png" },
  { name: "Disco Ball 8", url: "disco/discoball_8.png" },
  { name: "Disco Ball 9", url: "disco/discoball_9.png" },
  { name: "Disco Ball 10", url: "disco/discoball_10.png" },
  { name: "Disco Ball 11", url: "disco/discoball_11.png" },
  { name: "Disco Ball 12", url: "disco/discoball_12.png" },
]
